spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sns?characterEncoding=UTF-8
    username: root
    password: 1234
mybatis:
  mapper-locations: mappers/*Mapper.xml